config/routes.rb
Rails.application.routes.draw do
 get 'top/main'
 post 'top/login'
 root 'top#main'
 get 'top/logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    if session[:login_uid] != nil
      render "main"
    else
      render "login"
    end
  end

  def login
    logger.debug params[:uid]
    if User.find_by(uid :params[:uid]) and User.find_by(pass :params[:pass])
      session[:login_uid] = params[:uid]
      redirect_to top_main_path
    else
      render "error"
    end
  end
  
  def logout
    session.delete(:login_uid)
    redirect_to top_main_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CS1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/error.html.erb
エラーです

<%= link_to '戻る', :back %>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post, data: {turbo:false} do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %><br>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %><br>
    <%= submit_tag '登録' %>
<% end %>

app/views/top/main.html.erb
<h1>ログイン中です</h1>

<%= link_to "ログアウト",top_logout_path %>